import artichoke from '../assets/Artichoke (IQF Frozen).jpeg'
import broccoli from '../assets/Broccoli (IQF Frozen).jpeg'
import carrots from '../assets/Carrots (IQF Frozen).jpeg'
import cauliflower from '../assets/Cauliflower (IQF Frozen).jpeg'
import favaBeans from '../assets/Fava Beans (IQF Frozen).jpeg'
import greenBeans1 from '../assets/Green Beans (IQF Frozen).jpeg'
import greenBeans2 from '../assets/Green Beans (IQF Frozen) 2.jpeg'
import lobedBroadBeans from '../assets/Lobed Broad Beans (IQF Frozen).jpeg'
import mixedVegetables from '../assets/Mixed Vegetables (IQF Frozen).jpeg'
import molokhia from '../assets/Molokhia (IQF Frozen).jpeg'
import okra from '../assets/Okra (IQF Frozen).jpg'
import onion from '../assets/Onion (IQF Frozen).webp'
import strawberry from '../assets/STRAWBERRY (IQF Frozen).jpeg'

import bgHero from '../assets/bg1.png'
import bgPickled from '../assets/pickledProducts.png'
import sherryPeppers from '../assets/Sherry Peppers (Pickled).jpeg'
import redJalapeno from '../assets/Red Jalapeño (Pickled).jpeg'
import greenJalapeno from '../assets/Green Jalapeño (Pickled).jpeg'
import pickledPeppers from '../assets/pickled yellow peppers.jpeg'
import pickledGarlic from '../assets/pickled younggreen garlic.jpeg'

const assetByName = {
  'Artichoke (IQF Frozen)': artichoke,
  'Broccoli (IQF Frozen)': broccoli,
  'Carrots (IQF Frozen)': carrots,
  'Cauliflower (IQF Frozen)': cauliflower,
  'Fava Beans (IQF Frozen)': favaBeans,
  'Green Beans (IQF Frozen)': greenBeans1,
  'Green Beans (IQF Frozen) 2': greenBeans2,
  'Lobed Broad Beans (IQF Frozen)': lobedBroadBeans,
  'Mixed Vegetables (IQF Frozen)': mixedVegetables,
  'Molokhia (IQF Frozen)': molokhia,
  'Okra (IQF Frozen)': okra,
  'Onion (IQF Frozen)': onion,
  'STRAWBERRY (IQF Frozen)': strawberry,
  'Sherry Peppers (Pickled)': sherryPeppers,
  'Red Jalapeño (Pickled)': redJalapeno,
  'Green Jalapeño (Pickled)': greenJalapeno,
  'pickled yellow peppers': pickledPeppers,
  'pickled younggreen garlic': pickledGarlic,
}

const buildProduct = ({
  id,
  slug,
  nameEn,
  nameAr,
  nameEs,
  nameIt,
  latin,
  months,
  descriptionEn,
  descriptionAr,
  descriptionEs,
  descriptionIt,
}) => ({
  id,
  slug,
  nameEn,
  nameAr,
  nameEs,
  nameIt,
  latin,
  months,
  image: assetByName[nameEn] || bgHero,
  descriptionEn,
  descriptionAr,
  descriptionEs,
  descriptionIt,
})

export const productCategories = {
  frozen: {
    id: 'frozen',
    slug: 'frozen',
    titleEn: 'Frozen Vegetables',
    titleAr: 'الخضروات المجمدة',
    titleEs: 'Verduras Congeladas',
    titleIt: 'Verdure Surgelate',
    descriptionEn: 'Premium IQF vegetable products processed under strict quality control for consistent quality and dependable export performance.',
    descriptionAr: 'منتجات خضروات IQF premium تتم معالجتها وفق أعلى معايير الجودة لتحقيق ثبات الجودة وأداء تصدير موثوق.',
    descriptionEs: 'Productos vegetales IQF premium procesados bajo un estricto control de calidad para lograr una calidad constante y un rendimiento de exportación fiable.',
    descriptionIt: 'Prodotti vegetali IQF premium lavorati con rigorosi controlli di qualità per una resa costante e un’esportazione affidabile.',
    ctaEn: 'Explore Frozen Vegetables',
    ctaAr: 'استعرض الخضروات المجمدة',
    ctaEs: 'Explorar Verduras Congeladas',
    ctaIt: 'Esplora Verdure Surgelate',
    heroImageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
    seoTitleEn: 'Frozen Vegetables | EgyGreenera',
    seoDescriptionEn: 'Discover premium IQF frozen vegetables sourced and processed in Egypt for export-ready quality.',
    products: [
      buildProduct({
        id: 'artichoke-iqf',
        slug: 'artichoke-iqf',
        nameEn: 'Artichoke (IQF Frozen)',
        nameAr: 'خرشوف (مجمد IQF)',
        nameEs: 'Alcachofa (Congelada IQF)',
        nameIt: 'Carciofo (Surgelato IQF)',
        latin: 'Cynara scolymus',
        months: [3, 4, 5, 6],
        descriptionEn: 'Carefully prepared artichoke hearts with a clean, natural taste and stable texture for premium foodservice use.',
        descriptionAr: 'قلوب الخرشوف المعدة بعناية بنكهة طبيعية نقية وقوام ثابت للاستخدام في خدمات الطعام المتميزة.',
        descriptionEs: 'Corazones de alcachofa cuidadosamente preparados con un sabor natural limpio y una textura estable para uso premium en foodservice.',
        descriptionIt: 'Cuori di carciofo preparati con cura con un gusto naturale pulito e una consistenza stabile per uso premium in foodservice.',
      }),
      buildProduct({
        id: 'broccoli-iqf',
        slug: 'broccoli-iqf',
        nameEn: 'Broccoli (IQF Frozen)',
        nameAr: 'بروكلي (مجمد IQF)',
        nameEs: 'Brócoli (Congelado IQF)',
        nameIt: 'Broccoli (Surgelato IQF)',
        latin: 'Brassica oleracea',
        months: [10, 11, 12, 1, 2],
        descriptionEn: 'Fresh broccoli florets frozen quickly to preserve color, texture, and nutritional value for ready-to-cook applications.',
        descriptionAr: 'أزهار البروكلي الطازجة المجمدة بسرعة تحافظ على اللون والقوام والقيمة الغذائية للتطبيقات الجاهزة للطهي.',
        descriptionEs: 'Los floretes de brócoli frescos congelados rápidamente para preservar color, textura y valor nutricional en aplicaciones listas para cocinar.',
        descriptionIt: 'Cimette di broccoli fresche surgelate rapidamente per preservare colore, consistenza e valore nutrizionale in applicazioni pronte per la cottura.',
      }),
      buildProduct({
        id: 'carrots-iqf',
        slug: 'carrots-iqf',
        nameEn: 'Carrots (IQF Frozen)',
        nameAr: 'جزر (مجمد IQF)',
        nameEs: 'Zanahorias (Congeladas IQF)',
        nameIt: 'Carote (Surgelate IQF)',
        latin: 'Daucus carota',
        months: [1, 2, 3, 11, 12],
        descriptionEn: 'Uniform carrot cuts frozen for soups, stews, and mixed vegetables without losing sweetness or firmness.',
        descriptionAr: 'قطع الجزر المتناسقة المجمدة للحساء واليخنات والخضروات المشكلة دون فقدان الحلاوة أو الصلابة.',
        descriptionEs: 'Cortes uniformes de zanahoria congelados para sopas, guisos y verduras mixtas sin perder dulzor ni firmeza.',
        descriptionIt: 'Tagli di carota uniformi surgelati per zuppe, stufati e verdure miste senza perdere dolcezza o consistenza.',
      }),
      buildProduct({
        id: 'cauliflower-iqf',
        slug: 'cauliflower-iqf',
        nameEn: 'Cauliflower (IQF Frozen)',
        nameAr: 'قرنبيط (مجمد IQF)',
        nameEs: 'Coliflor (Congelada IQF)',
        nameIt: 'Cavolfiore (Surgelato IQF)',
        latin: 'Brassica oleracea',
        months: [1, 2, 3, 11, 12],
        descriptionEn: 'High-quality cauliflower florets preserved for culinary use with dependable texture and a naturally bright appearance.',
        descriptionAr: 'أزهار القرنبيط عالية الجودة محفوظة للاستخدام الطهوي مع قوام موثوق ومظهر طبيعي مشرق.',
        descriptionEs: 'Floretas de coliflor de alta calidad conservadas para uso culinario con textura fiable y apariencia naturalmente brillante.',
        descriptionIt: 'Cimette di cavolfiore di alta qualità conservate per uso culinario con consistenza affidabile e aspetto naturalmente brillante.',
      }),
      buildProduct({
        id: 'fava-beans-iqf',
        slug: 'fava-beans-iqf',
        nameEn: 'Fava Beans (IQF Frozen)',
        nameAr: 'فول (مجمد IQF)',
        nameEs: 'Habas (Congeladas IQF)',
        nameIt: 'Fave (Surgelate IQF)',
        latin: 'Vicia faba',
        months: [11, 12, 1, 2, 3],
        descriptionEn: 'Tender fava beans kept in a stable frozen state to preserve their classic taste and clean, healthy finish.',
        descriptionAr: 'الفول الطري محتفظ به في حالة مجمدة مستقرة للحفاظ على طعمه الكلاسيكي ونهايته النظيفة والصحية.',
        descriptionEs: 'Habas tiernas mantenidas en estado congelado para conservar su sabor clásico y un final limpio y saludable.',
        descriptionIt: 'Fave tenere mantenute nello stato surgelato per conservare il gusto classico e una chiusura pulita e salutare.',
      }),
      buildProduct({
        id: 'green-beans-iqf',
        slug: 'green-beans-iqf',
        nameEn: 'Green Beans (IQF Frozen)',
        nameAr: 'فاصوليا خضراء (مجمدة IQF)',
        nameEs: 'Judías Verdes (Congeladas IQF)',
        nameIt: 'Fagiolini Verdi (Surgelati IQF)',
        latin: 'Phaseolus vulgaris',
        months: [4, 5, 6, 7, 8],
        descriptionEn: 'Green beans frozen at peak quality for consistent color, texture, and cooking performance in industrial and retail kitchens.',
        descriptionAr: 'الفاصوليا الخضراء المجمدة في ذروة الجودة لضمان اللون والقوام والأداء الطهوي في المطابخ الصناعية والتجزئة.',
        descriptionEs: 'Judías verdes congeladas en su máximo nivel de calidad para una textura, color y rendimiento culinario consistentes en cocinas industriales y minoristas.',
        descriptionIt: 'Fagiolini verdi surgelati al massimo della qualità per una consistenza, colore e prestazione culinaria costanti in cucine industriali e retail.',
      }),
      buildProduct({
        id: 'lobed-broad-beans-iqf',
        slug: 'lobed-broad-beans-iqf',
        nameEn: 'Lobed Broad Beans (IQF Frozen)',
        nameAr: 'فول مجدول (مجمد IQF)',
        nameEs: 'Habas de Haba Lobuladas (Congeladas IQF)',
        nameIt: 'Fave Lobate (Surgelate IQF)',
        latin: 'Vicia faba',
        months: [11, 12, 1, 2],
        descriptionEn: 'Large broad beans sorted and frozen to maintain their tender bite and naturally green appearance.',
        descriptionAr: 'الفول الكبير المصنف والمجمد للحفاظ على قرمشته الطرية والمظهر الأخضر الطبيعي.',
        descriptionEs: 'Habas grandes clasificadas y congeladas para mantener su textura tierna y apariencia verde natural.',
        descriptionIt: 'Fave grandi selezionate e surgelate per mantenere il morso tenero e l’aspetto verde naturale.',
      }),
      buildProduct({
        id: 'mixed-vegetables-iqf',
        slug: 'mixed-vegetables-iqf',
        nameEn: 'Mixed Vegetables (IQF Frozen)',
        nameAr: 'خضروات مشكلة (مجمدة IQF)',
        nameEs: 'Verduras Mixtas (Congeladas IQF)',
        nameIt: 'Verdure Miste (Surgelate IQF)',
        latin: 'Mixed vegetables',
        months: [1, 2, 3, 11, 12],
        descriptionEn: 'Balanced vegetable mix for consistent taste, color retention, and foodservice convenience.',
        descriptionAr: 'خليط متوازن من الخضروات لضمان النكهة الثابتة واللون والحالة المريحة لخدمات الطعام.',
        descriptionEs: 'Mezcla equilibrada de verduras para sabor constante, retención de color y conveniencia para foodservice.',
        descriptionIt: 'Miscela equilibrata di verdure per gusto costante, mantenimento del colore e praticità per il foodservice.',
      }),
      buildProduct({
        id: 'molokhia-iqf',
        slug: 'molokhia-iqf',
        nameEn: 'Molokhia (IQF Frozen)',
        nameAr: 'ملوخية (مجمدة IQF)',
        nameEs: 'Molokhia (Congelada IQF)',
        nameIt: 'Molokhia (Surgelata IQF)',
        latin: 'Corchorus olitorius',
        months: [6, 7, 8, 9],
        descriptionEn: 'Selected leafy greens processed with rapid freezing to keep the traditional fresh flavor and deep green look.',
        descriptionAr: 'الأوراق المختارة المعالجة بالتجميد السريع للحفاظ على الطعم الطازج التقليدي والمظهر الأخضر العميق.',
        descriptionEs: 'Hojas seleccionadas procesadas con congelación rápida para mantener el sabor fresco tradicional y un verde intenso.',
        descriptionIt: 'Foglie selezionate lavorate con rapid freezing per mantenere il gusto tradizionale fresco e un verde profondo.',
      }),
      buildProduct({
        id: 'okra-iqf',
        slug: 'okra-iqf',
        nameEn: 'Okra (IQF Frozen)',
        nameAr: 'بامية (مجمدة IQF)',
        nameEs: 'Okra (Congelada IQF)',
        nameIt: 'Ocra (Surgelata IQF)',
        latin: 'Abelmoschus esculentus',
        months: [6, 7, 8, 9, 10],
        descriptionEn: 'Fresh okra pods quick-frozen to maintain tenderness, green color, and consistent size from harvest to kitchen.',
        descriptionAr: 'قرون البامية الطازجة المجمدة بسرعة للحفاظ على الطراوة واللون الأخضر والحجم المتسق من الحصاد إلى المطبخ.',
        descriptionEs: 'Vainas frescas de okra congeladas rápidamente para mantener ternura, color verde y tamaño consistente desde la cosecha hasta la cocina.',
        descriptionIt: 'Gambi di okra freschi surgelati rapidamente per mantenere tenerezza, colore verde e dimensione costante dalla raccolta alla cucina.',
      }),
      buildProduct({
        id: 'onion-iqf',
        slug: 'onion-iqf',
        nameEn: 'Onion (IQF Frozen)',
        nameAr: 'بصل (مجمد IQF)',
        nameEs: 'Cebolla (Congelada IQF)',
        nameIt: 'Cipolla (Surgelata IQF)',
        latin: 'Allium cepa',
        months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        descriptionEn: 'Uniform frozen onion pieces designed for consistent flavor release and reliable performance in industrial kitchens and foodservice prep.',
        descriptionAr: 'قطع البصل المجمدة المتناسقة المصممة لتحقيق نكهة متسقة وأداء موثوق في المطابخ الصناعية وخدمات الطعام.',
        descriptionEs: 'Piezas uniformes de cebolla congelada diseñadas para un sabor constante y un rendimiento fiable en cocinas industriales y preparación de foodservice.',
        descriptionIt: 'Pezzetti uniformi di cipolla surgelata progettati per un gusto costante e una resa affidabile in cucine industriali e preparazioni foodservice.',
      }),
      buildProduct({
        id: 'strawberry-iqf',
        slug: 'strawberry-iqf',
        nameEn: 'STRAWBERRY (IQF Frozen)',
        nameAr: 'فراولة (مجمدة IQF)',
        nameEs: 'Fresa (Congelada IQF)',
        nameIt: 'Fragola (Surgelata IQF)',
        latin: 'Fragaria × ananassa',
        months: [1, 2, 3, 4, 12],
        descriptionEn: 'Premium frozen strawberries preserved at the ideal ripeness stage for flavor, color, and texture in bakery and foodservice applications.',
        descriptionAr: 'الفراولة المميزة المجمدة عند المرحلة المثالية للحفاظ على النكهة واللون والقوام في استخدامات المخابز وخدمات الطعام.',
        descriptionEs: 'Fresas premium congeladas en el punto de maduración ideal para mantener sabor, color y textura en aplicaciones de panadería y foodservice.',
        descriptionIt: 'Fragole premium surgelate nel punto di maturazione ideale per mantenere gusto, colore e consistenza in applicazioni da pasticceria e foodservice.',
      }),
    ],
  },

  pickled: {
    id: 'pickled',
    slug: 'pickled',
    titleEn: 'Pickled Products',
    titleAr: 'المنتجات المخللة',
    titleEs: 'Productos Encurtidos',
    titleIt: 'Prodotti Sottaceto',
    descriptionEn: 'Traditional pickled vegetables prepared with controlled brine and quality ingredients to preserve authentic taste and texture.',
    descriptionAr: 'خضروات مخللة تقليدية تُحضّر بمحلول مملح مُتحكم به ومكونات عالية الجودة للحفاظ على الطعم والقوام الأصليين.',
    descriptionEs: 'Verduras encurtidas tradicionales preparadas con salmuera controlada e ingredientes de calidad para preservar el sabor y la textura auténticos.',
    descriptionIt: 'Verdure sottaceto tradizionali preparate con salamoia controllata e ingredienti di qualità per preservare gusto e consistenza autentici.',
    ctaEn: 'Explore Pickled Products',
    ctaAr: 'استعرض المنتجات المخللة',
    ctaEs: 'Explorar Productos Encurtidos',
    ctaIt: 'Esplora Prodotti Sottaceto',
    heroImageUrl: 'https://images.unsplash.com/photo-1582515073490-39981397c445?auto=format&fit=crop&w=1400&q=80',
    seoTitleEn: 'Pickled Products | EgyGreenera',
    seoDescriptionEn: 'Explore pickled vegetables prepared with traditional methods and premium ingredients.',
    products: [
      buildProduct({
        id: 'sherry-peppers-pickled',
        slug: 'sherry-peppers-pickled',
        nameEn: 'Sherry Peppers (Pickled)',
        nameAr: 'فلفل شيري (مخلل)',
        nameEs: 'Pimientos Sherry (Encurtidos)',
        nameIt: 'Peperoni Sherry (Sottaceto)',
        latin: 'Capsicum annuum',
        months: [6, 7, 8, 9],
        descriptionEn: 'Sherry peppers preserved in brine for a vibrant, savory flavor and crisp bite suitable for premium foodservice and retail use.',
        descriptionAr: 'فلفل شيري محفوظ في المحلول الملحي بنكهة نابضة بالحياة ومذاق متبل وقرمشة ممتازة مناسبة للاستخدام المتميز في خدمات الطعام والتجزئة.',
        descriptionEs: 'Pimientos Sherry conservados en salmuera para un sabor vibrante, sabroso y un toque crujiente ideal para foodservice premium y retail.',
        descriptionIt: 'Peperoni Sherry conservati in salamoia per un gusto vibrante, saporito e croccante adatto a foodservice premium e retail.',
      }),
      buildProduct({
        id: 'red-jalapeno-pickled',
        slug: 'red-jalapeno-pickled',
        nameEn: 'Red Jalapeño (Pickled)',
        nameAr: 'هالابينو أحمر (مخلل)',
        nameEs: 'Jalapeño Rojo (Encurtido)',
        nameIt: 'Jalapeño Rosso (Sottaceto)',
        latin: 'Capsicum annuum',
        months: [5, 6, 7, 8, 9],
        descriptionEn: 'Red jalapeño slices preserved in brine to deliver a medium heat, bright color, and a clean, balanced pickle finish.',
        descriptionAr: 'شرائح الهالابينو الأحمر المحفوظة في المحلول الملحي تعطي حرارة متوسطة، لونًا مشرقًا، ونهاية مخللة متوازنة ونظيفة.',
        descriptionEs: 'Rodajas de jalapeño rojo conservadas en salmuera para ofrecer un calor medio, color brillante y un final encurtido limpio y equilibrado.',
        descriptionIt: 'Fette di jalapeño rosso conservate in salamoia per un calore medio, colore brillante e un finale sottaceto pulito ed equilibrato.',
      }),
      buildProduct({
        id: 'green-jalapeno-pickled',
        slug: 'green-jalapeno-pickled',
        nameEn: 'Green Jalapeño (Pickled)',
        nameAr: 'هالابينو أخضر (مخلل)',
        nameEs: 'Jalapeño Verde (Encurtido)',
        nameIt: 'Jalapeño Verde (Sottaceto)',
        latin: 'Capsicum annuum',
        months: [5, 6, 7, 8, 9],
        descriptionEn: 'Green jalapeño rings preserved in brine with a crisp texture and fresh heat profile for versatile culinary applications.',
        descriptionAr: 'حلقات الهالابينو الأخضر المحفوظة في المحلول الملحي بقوام مقرمش ونكهة حارة منعشة مناسبة لتطبيقات الطهي المتنوعة.',
        descriptionEs: 'Anillos de jalapeño verde conservados en salmuera con textura crujiente y perfil picante fresco para aplicaciones culinarias versátiles.',
        descriptionIt: 'Anelli di jalapeño verde conservati in salamoia con texture croccante e profilo piccante fresco per applicazioni culinarie versatili.',
      }),
      buildProduct({
        id: 'pickled-yellow-peppers',
        slug: 'pickled-yellow-peppers',
        nameEn: 'pickled yellow peppers',
        nameAr: 'فلفل أصفر مخلل',
        nameEs: 'pimientos amarillos encurtidos',
        nameIt: 'peperoni gialli sottaceto',
        latin: 'Capsicum annuum',
        months: [6, 7, 8, 9],
        descriptionEn: 'Yellow peppers fermented and packed in brine for a bright, savory, and balanced pickle profile.',
        descriptionAr: 'فلفل أصفر مُخمر ومعبأ في المحلول الملحي ليعطي نكهة مشرقة ومتوازنة ومتبلة.',
        descriptionEs: 'Pimientos amarillos fermentados y envasados en salmuera para un perfil brillante, sabroso y equilibrado.',
        descriptionIt: 'Peperoni gialli fermentati e confezionati in salamoia per un profilo brillante, saporito ed equilibrato.',
      }),
      buildProduct({
        id: 'pickled-young-garlic',
        slug: 'pickled-young-garlic',
        nameEn: 'pickled younggreen garlic',
        nameAr: 'ثوم صغير مخلل',
        nameEs: 'ajo joven en escabeche',
        nameIt: 'aglio giovane sottaceto',
        latin: 'Allium sativum',
        months: [1, 2, 3, 12],
        descriptionEn: 'Young garlic preserved in brine with a traditional aromatic profile for a clean and savory bite.',
        descriptionAr: 'ثوم صغير محفوظ في المحلول الملحي بنكهة عطريّة تقليدية وقرمشة نظيفة وطعم متبل.',
        descriptionEs: 'Ajo joven conservado en salmuera con un perfil aromático tradicional para un mordisco limpio y sabroso.',
        descriptionIt: 'Aglio giovane conservato in salamoia con profilo aromatizzato tradizionale per un morso pulito e saporito.',
      }),
    ],
  },
}

export function getCategory(categoryId) {
  return productCategories[categoryId]
}

export function getCategoryTitle(categoryId, language = 'en') {
  const category = getCategory(categoryId)
  if (!category) return ''

  const key = `title${language.charAt(0).toUpperCase() + language.slice(1)}`
  return category[key] || category.titleEn
}

export function getCategoryProducts(categoryId) {
  const category = getCategory(categoryId)
  return category?.products || []
}
